// 170/src/pages/Address.tsx
import React, { useState } from 'react';
import { Card, List, Button, Modal, Form, Input, Switch, message } from 'antd';
import {
  PlusOutlined,
  EditOutlined,
  DeleteOutlined,
  EnvironmentOutlined,
  PhoneOutlined,
  UserOutlined,
} from '@ant-design/icons';
import { useAppSelector, useAppDispatch } from '../store';
import { addAddress, updateAddress, deleteAddress } from '../store/modules/user';
import type { Address } from '../types';
import EmptyState from '../components/common/EmptyState';
import { validatePhone } from '../utils';

interface AddressFormValues {
  name: string;
  phone: string;
  province: string;
  city: string;
  district: string;
  detail: string;
  isDefault: boolean;
}

const Address: React.FC = () => {
  const dispatch = useAppDispatch();
  const { currentUser } = useAppSelector((state) => state.user);
  const addresses = currentUser?.address || [];

  const [modalVisible, setModalVisible] = useState(false);
  const [editingAddress, setEditingAddress] = useState<Address | null>(null);
  const [form] = Form.useForm<AddressFormValues>();

  const handleAdd = () => {
    setEditingAddress(null);
    form.resetFields();
    setModalVisible(true);
  };

  const handleEdit = (address: Address) => {
    setEditingAddress(address);
    form.setFieldsValue(address);
    setModalVisible(true);
  };

  const handleDelete = (id: string) => {
    Modal.confirm({
      title: '确认删除',
      content: '您确定要删除这个地址吗？',
      onOk: () => {
        dispatch(deleteAddress(id));
        message.success('删除成功');
      },
    });
  };

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();
      
      if (editingAddress) {
        dispatch(updateAddress({ ...editingAddress, ...values }));
        message.success('地址更新成功');
      } else {
        const newAddress: Address = {
          id: Date.now().toString(),
          ...values,
        };
        dispatch(addAddress(newAddress));
        message.success('地址添加成功');
      }
      
      setModalVisible(false);
    } catch (error) {
      console.error('表单验证失败:', error);
    }
  };

  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', padding: '24px' }}>
      <Card
        title="地址管理"
        extra={
          <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
            新增地址
          </Button>
        }
      >
        {addresses.length > 0 ? (
          <List
            dataSource={addresses}
            renderItem={(item) => (
              <List.Item
                key={item.id}
                style={{
                  border: '1px solid #f0f0f0',
                  borderRadius: '8px',
                  marginBottom: '12px',
                  padding: '16px',
                }}
              >
                <div style={{ flex: 1 }}>
                  <div style={{ display: 'flex', alignItems: 'center', marginBottom: '8px' }}>
                    <span style={{ fontWeight: 'bold', fontSize: '16px', marginRight: '12px' }}>
                      {item.name}
                    </span>
                    <span style={{ color: '#666', marginRight: '12px' }}>
                      <PhoneOutlined style={{ marginRight: '4px' }} />
                      {item.phone}
                    </span>
                    {item.isDefault && (
                      <span
                        style={{
                          background: '#1890ff',
                          color: '#fff',
                          padding: '2px 8px',
                          borderRadius: '4px',
                          fontSize: '12px',
                        }}
                      >
                        默认
                      </span>
                    )}
                  </div>
                  <div style={{ color: '#666' }}>
                    <EnvironmentOutlined style={{ marginRight: '4px' }} />
                    {item.province} {item.city} {item.district} {item.detail}
                  </div>
                </div>
                <div style={{ display: 'flex', gap: '8px' }}>
                  <Button type="link" icon={<EditOutlined />} onClick={() => handleEdit(item)}>
                    编辑
                  </Button>
                  <Button type="link" danger icon={<DeleteOutlined />} onClick={() => handleDelete(item.id)}>
                    删除
                  </Button>
                </div>
              </List.Item>
            )}
          />
        ) : (
          <EmptyState description="暂无收货地址" actionText="添加地址" actionPath="/address" />
        )}
      </Card>

      <Modal
        title={editingAddress ? '编辑地址' : '新增地址'}
        open={modalVisible}
        onOk={handleSubmit}
        onCancel={() => setModalVisible(false)}
        okText="保存"
        cancelText="取消"
        width={500}
      >
        <Form form={form} layout="vertical" initialValues={{ isDefault: false }}>
          <div style={{ display: 'flex', gap: '16px' }}>
            <Form.Item
              name="name"
              label="收货人姓名"
              rules={[{ required: true, message: '请输入收货人姓名' }]}
              style={{ flex: 1 }}
            >
              <Input prefix={<UserOutlined />} placeholder="请输入姓名" />
            </Form.Item>
            <Form.Item
              name="phone"
              label="联系电话"
              rules={[
                { required: true, message: '请输入联系电话' },
                {
                  validator: (_, value) => {
                    if (!value) return Promise.resolve();
                    if (validatePhone(value)) {
                      return Promise.resolve();
                    }
                    return Promise.reject(new Error('请输入正确的手机号'));
                  },
                },
              ]}
              style={{ flex: 1 }}
            >
              <Input prefix={<PhoneOutlined />} placeholder="请输入手机号" maxLength={11} />
            </Form.Item>
          </div>
          <div style={{ display: 'flex', gap: '16px' }}>
            <Form.Item
              name="province"
              label="省份"
              rules={[{ required: true, message: '请输入省份' }]}
              style={{ flex: 1 }}
            >
              <Input placeholder="请输入省份" />
            </Form.Item>
            <Form.Item
              name="city"
              label="城市"
              rules={[{ required: true, message: '请输入城市' }]}
              style={{ flex: 1 }}
            >
              <Input placeholder="请输入城市" />
            </Form.Item>
            <Form.Item
              name="district"
              label="区县"
              rules={[{ required: true, message: '请输入区县' }]}
              style={{ flex: 1 }}
            >
              <Input placeholder="请输入区县" />
            </Form.Item>
          </div>
          <Form.Item
            name="detail"
            label="详细地址"
            rules={[{ required: true, message: '请输入详细地址' }]}
          >
            <Input placeholder="请输入详细地址" />
          </Form.Item>
          <Form.Item name="isDefault" label="设为默认地址" valuePropName="checked">
            <Switch />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

export default Address;

// 163/src/views/profile/Address.vue
<template>
  <div class="address-page">
    <div class="page-header">
      <h2 class="page-title">收货地址</h2>
      <el-button type="primary" @click="handleAdd">
        <el-icon><Plus /></el-icon>
        新增地址
      </el-button>
    </div>

    <div v-if="userStore.addresses.length > 0" class="address-list">
      <div
        v-for="addr in userStore.addresses"
        :key="addr.id"
        class="address-card"
        :class="{ default: addr.isDefault }"
      >
        <div class="address-info">
          <div class="address-header">
            <span class="name">{{ addr.name }}</span>
            <span class="phone">{{ addr.phone }}</span>
            <el-tag v-if="addr.isDefault" type="primary" size="small">默认</el-tag>
          </div>
          <div class="address-detail">
            {{ addr.province }}{{ addr.city }}{{ addr.district }}{{ addr.address }}
          </div>
        </div>
        <div class="address-actions">
          <el-button type="primary" link @click="handleEdit(addr)">
            <el-icon><Edit /></el-icon>
            编辑
          </el-button>
          <el-button v-if="!addr.isDefault" type="primary" link @click="handleSetDefault(addr)">
            设为默认
          </el-button>
          <el-button type="danger" link @click="handleDelete(addr)">
            <el-icon><Delete /></el-icon>
            删除
          </el-button>
        </div>
      </div>
    </div>

    <div v-else class="empty-wrapper">
      <el-empty description="暂无收货地址">
        <el-button type="primary" @click="handleAdd">添加地址</el-button>
      </el-empty>
    </div>

    <el-dialog
      v-model="showDialog"
      :title="editingAddress ? '编辑地址' : '新增地址'"
      width="500px"
    >
      <el-form
        ref="formRef"
        :model="form"
        :rules="rules"
        label-width="80px"
      >
        <el-form-item label="收货人" prop="name">
          <el-input v-model="form.name" placeholder="请输入收货人姓名" />
        </el-form-item>
        <el-form-item label="手机号" prop="phone">
          <el-input v-model="form.phone" placeholder="请输入手机号" />
        </el-form-item>
        <el-form-item label="省市区" prop="province">
          <el-row :gutter="12">
            <el-col :span="8">
              <el-input v-model="form.province" placeholder="省份" />
            </el-col>
            <el-col :span="8">
              <el-input v-model="form.city" placeholder="城市" />
            </el-col>
            <el-col :span="8">
              <el-input v-model="form.district" placeholder="区县" />
            </el-col>
          </el-row>
        </el-form-item>
        <el-form-item label="详细地址" prop="address">
          <el-input
            v-model="form.address"
            type="textarea"
            :rows="2"
            placeholder="请输入详细地址"
          />
        </el-form-item>
        <el-form-item label="设为默认">
          <el-switch v-model="form.isDefault" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="showDialog = false">取消</el-button>
        <el-button type="primary" @click="handleSubmit">确定</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus, Edit, Delete } from '@element-plus/icons-vue'
import { useUserStore } from '@/stores/user'
import { validatePhone } from '@/utils'

const userStore = useUserStore()

const showDialog = ref(false)
const editingAddress = ref(null)
const formRef = ref(null)

const form = reactive({
  name: '',
  phone: '',
  province: '',
  city: '',
  district: '',
  address: '',
  isDefault: false
})

const rules = {
  name: [
    { required: true, message: '请输入收货人姓名', trigger: 'blur' }
  ],
  phone: [
    { required: true, message: '请输入手机号', trigger: 'blur' },
    {
      validator: (rule, value, callback) => {
        if (!validatePhone(value)) {
          callback(new Error('请输入正确的手机号'))
        } else {
          callback()
        }
      },
      trigger: 'blur'
    }
  ],
  province: [{ required: true, message: '请输入省份', trigger: 'blur' }],
  city: [{ required: true, message: '请输入城市', trigger: 'blur' }],
  district: [{ required: true, message: '请输入区县', trigger: 'blur' }],
  address: [{ required: true, message: '请输入详细地址', trigger: 'blur' }]
}

const handleAdd = () => {
  editingAddress.value = null
  Object.assign(form, {
    name: '',
    phone: '',
    province: '',
    city: '',
    district: '',
    address: '',
    isDefault: false
  })
  showDialog.value = true
}

const handleEdit = (addr) => {
  editingAddress.value = addr
  Object.assign(form, { ...addr })
  showDialog.value = true
}

const handleSetDefault = (addr) => {
  userStore.updateAddress(addr.id, { isDefault: true })
  ElMessage.success('已设为默认地址')
}

const handleDelete = (addr) => {
  ElMessageBox.confirm('确定要删除该地址吗？', '提示', {
    confirmButtonText: '确定',
    cancelButtonText: '取消',
    type: 'warning'
  }).then(() => {
    userStore.deleteAddress(addr.id)
    ElMessage.success('已删除')
  }).catch(() => {})
}

const handleSubmit = () => {
  formRef.value.validate((valid) => {
    if (valid) {
      if (editingAddress.value) {
        userStore.updateAddress(editingAddress.value.id, { ...form })
        ElMessage.success('修改成功')
      } else {
        userStore.addAddress({ ...form })
        ElMessage.success('添加成功')
      }
      showDialog.value = false
    }
  })
}
</script>

<style lang="scss" scoped>
.address-page {
  .page-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 20px;
  }

  .address-list {
    display: flex;
    flex-direction: column;
    gap: 16px;
  }

  .address-card {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    padding: 20px;
    border: 2px solid #e4e7ed;
    border-radius: 8px;
    transition: all 0.3s;

    &.default {
      border-color: #409eff;
      background-color: #f0f9ff;
    }

    &:hover {
      border-color: #409eff;
    }
  }

  .address-info {
    flex: 1;

    .address-header {
      display: flex;
      align-items: center;
      gap: 12px;
      margin-bottom: 8px;

      .name {
        font-size: 16px;
        font-weight: 600;
        color: #333;
      }

      .phone {
        color: #666;
        font-size: 14px;
      }
    }

    .address-detail {
      color: #666;
      font-size: 14px;
      line-height: 1.6;
    }
  }

  .address-actions {
    display: flex;
    gap: 16px;
    flex-shrink: 0;
  }
}

@media (max-width: 768px) {
  .address-card {
    flex-direction: column;
    gap: 16px;
  }

  .address-actions {
    width: 100%;
    justify-content: flex-start;
  }
}
</style>
