// 171/src/components/AppHeader.jsx
import { useState, useMemo } from 'react'
import { Layout, Menu, Dropdown, Avatar, Button, Space, Select } from 'antd'
import {
  HomeOutlined,
  UserOutlined,
  LogoutOutlined,
  ShoppingOutlined,
  EnvironmentOutlined,
} from '@ant-design/icons'
import { Link, useNavigate, useLocation } from 'react-router-dom'
import { useSelector, useDispatch } from 'react-redux'
import { setCity } from '@/store/slices/serviceSlice'
import { logout } from '@/store/slices/userSlice'

const { Header } = Layout
const { Option } = Select

function AppHeader() {
  const navigate = useNavigate()
  const location = useLocation()
  const dispatch = useDispatch()
  const { currentUser } = useSelector((state) => state.user)
  const { currentCity, cities } = useSelector((state) => state.service)

  const selectedKey = useMemo(() => {
    if (location.pathname.startsWith('/user') || location.pathname.startsWith('/cleaner')) {
      return 'center'
    }
    return location.pathname === '/' ? 'home' : ''
  }, [location.pathname])

  const handleCityChange = (value) => {
    dispatch(setCity(value))
  }

  const handleLogout = () => {
    dispatch(logout())
    navigate('/')
  }

  const userMenu = {
    items: [
      {
        key: 'center',
        icon: <UserOutlined />,
        label: currentUser?.role === 'cleaner' ? '保洁师中心' : '个人中心',
        onClick: () => navigate(currentUser?.role === 'cleaner' ? '/cleaner' : '/user'),
      },
      {
        key: 'orders',
        icon: <ShoppingOutlined />,
        label: '我的订单',
        onClick: () => navigate(currentUser?.role === 'cleaner' ? '/cleaner/orders' : '/user/orders'),
      },
      { type: 'divider' },
      {
        key: 'logout',
        icon: <LogoutOutlined />,
        label: '退出登录',
        onClick: handleLogout,
      },
    ],
  }

  return (
    <Header
      style={{
        background: '#fff',
        boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
        padding: '0 24px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        position: 'sticky',
        top: 0,
        zIndex: 100,
      }}
    >
      <div style={{ display: 'flex', alignItems: 'center', gap: 24 }}>
        <Link to="/" style={{ display: 'flex', alignItems: 'center' }}>
          <div
            style={{
              fontSize: 20,
              fontWeight: 700,
              color: '#1890ff',
              display: 'flex',
              alignItems: 'center',
              gap: 8,
            }}
          >
            <span style={{ fontSize: 24 }}>🧹</span>
            洁家上门保洁
          </div>
        </Link>

        <Space>
          <EnvironmentOutlined style={{ color: '#999' }} />
          <Select
            value={currentCity}
            onChange={handleCityChange}
            style={{ width: 120 }}
            bordered={false}
          >
            {cities.map((city) => (
              <Option key={city} value={city}>
                {city}
              </Option>
            ))}
          </Select>
        </Space>

        <Menu
          mode="horizontal"
          selectedKeys={[selectedKey]}
          style={{ flex: 1, minWidth: 400, borderBottom: 'none' }}
          items={[
            { key: 'home', label: <Link to="/">首页</Link>, icon: <HomeOutlined /> },
          ]}
        />
      </div>

      <div>
        {currentUser ? (
          <Dropdown menu={userMenu} placement="bottomRight">
            <Space style={{ cursor: 'pointer', padding: '8px 12px', borderRadius: 4 }}>
              <Avatar src={currentUser.avatar} size="small" />
              <span>{currentUser.name}</span>
            </Space>
          </Dropdown>
        ) : (
          <Space>
            <Button type="text" onClick={() => navigate('/login')}>
              登录
            </Button>
            <Button type="primary" onClick={() => navigate('/register')}>
              注册
            </Button>
          </Space>
        )}
      </div>
    </Header>
  )
}

export default AppHeader

// 180/baking-platform/src/components/AppHeader.vue
<script setup>
import { ref, computed } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { ElMessage } from 'element-plus'
import { useUserStore } from '../stores/user'

const router = useRouter()
const route = useRoute()
const userStore = useUserStore()
const searchKeyword = ref('')

const isLoggedIn = computed(() => userStore.isLoggedIn)
const userInfo = computed(() => userStore.userInfo)
const isMerchant = computed(() => userInfo.value?.role === 'merchant')

const menuItems = [
  { name: '首页', path: '/' },
]

function handleSearch() {
  if (searchKeyword.value.trim()) {
    ElMessage.info(`搜索: ${searchKeyword.value}`)
  }
}

function handleLogout() {
  userStore.logout()
  ElMessage.success('退出登录成功')
  router.push('/')
}

function goToCenter() {
  if (isMerchant.value) {
    router.push('/merchant')
  } else {
    router.push('/user')
  }
}
</script>

<template>
  <header class="app-header">
    <div class="header-content">
      <div class="logo" @click="router.push('/')">
        <el-icon :size="32" color="#e6a23c"><Goods /></el-icon>
        <span class="logo-text">烘焙原料商城</span>
      </div>
      
      <nav class="nav-menu">
        <router-link 
          v-for="item in menuItems" 
          :key="item.path" 
          :to="item.path"
          class="nav-item"
          :class="{ active: route.path === item.path }"
        >
          {{ item.name }}
        </router-link>
      </nav>

      <div class="header-right">
        <div class="search-box">
          <el-input
            v-model="searchKeyword"
            placeholder="搜索烘焙原料..."
            class="search-input"
            @keyup.enter="handleSearch"
          >
            <template #append>
              <el-button @click="handleSearch">
                <el-icon><Search /></el-icon>
              </el-button>
            </template>
          </el-input>
        </div>

        <div class="user-area">
          <template v-if="isLoggedIn">
            <el-dropdown>
              <span class="user-info">
                <el-avatar :size="32" :src="userInfo?.avatar" />
                <span class="user-name">{{ userInfo?.nickname }}</span>
                <el-icon><ArrowDown /></el-icon>
              </span>
              <template #dropdown>
                <el-dropdown-menu>
                  <el-dropdown-item @click="goToCenter">
                    <el-icon><User /></el-icon>
                    {{ isMerchant ? '商家中心' : '个人中心' }}
                  </el-dropdown-item>
                  <el-dropdown-item divided @click="handleLogout">
                    <el-icon><SwitchButton /></el-icon>
                    退出登录
                  </el-dropdown-item>
                </el-dropdown-menu>
              </template>
            </el-dropdown>
          </template>
          <template v-else>
            <el-button text @click="router.push('/login')">登录</el-button>
            <el-button type="primary" @click="router.push('/register')">注册</el-button>
          </template>
        </div>
      </div>
    </div>
  </header>
</template>

<style scoped>
.app-header {
  background: #fff;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  position: sticky;
  top: 0;
  z-index: 100;
}

.header-content {
  width: 1200px;
  margin: 0 auto;
  height: 70px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 20px;
}

.logo {
  display: flex;
  align-items: center;
  gap: 10px;
  cursor: pointer;
}

.logo-text {
  font-size: 20px;
  font-weight: 600;
  color: #e6a23c;
}

.nav-menu {
  display: flex;
  gap: 30px;
  margin-left: 40px;
}

.nav-item {
  color: #606266;
  font-size: 16px;
  text-decoration: none;
  padding: 8px 0;
  position: relative;
  transition: color 0.3s;
}

.nav-item:hover,
.nav-item.active {
  color: #e6a23c;
}

.nav-item.active::after {
  content: '';
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  height: 2px;
  background: #e6a23c;
}

.header-right {
  display: flex;
  align-items: center;
  gap: 20px;
}

.search-box {
  width: 300px;
}

.user-area {
  display: flex;
  align-items: center;
  gap: 10px;
}

.user-info {
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
  padding: 5px 10px;
  border-radius: 20px;
  transition: background 0.3s;
}

.user-info:hover {
  background: #f5f7fa;
}

.user-name {
  font-size: 14px;
  color: #606266;
}
</style>
