// 183/src/views/Register.vue
<template>
  <div class="register-page">
    <div class="register-container">
      <div class="register-card">
        <div class="register-header">
          <el-icon :size="48" color="#8b6914"><Camera /></el-icon>
          <h1 class="register-title">创建账户</h1>
          <p class="register-subtitle">加入复古胶片相机爱好者社区</p>
        </div>
        
        <el-form 
          ref="registerFormRef"
          :model="registerForm" 
          :rules="registerRules" 
          class="register-form"
          label-width="100px"
        >
          <el-form-item label="用户名" prop="username">
            <el-input 
              v-model="registerForm.username" 
              placeholder="请输入用户名" 
              size="large"
            />
          </el-form-item>
          
          <el-form-item label="昵称" prop="nickname">
            <el-input 
              v-model="registerForm.nickname" 
              placeholder="请输入昵称" 
              size="large"
            />
          </el-form-item>
          
          <el-form-item label="邮箱" prop="email">
            <el-input 
              v-model="registerForm.email" 
              placeholder="请输入邮箱地址" 
              size="large"
            />
          </el-form-item>
          
          <el-form-item label="手机号" prop="phone">
            <el-input 
              v-model="registerForm.phone" 
              placeholder="请输入手机号码" 
              size="large"
            />
          </el-form-item>
          
          <el-form-item label="密码" prop="password">
            <el-input 
              v-model="registerForm.password" 
              type="password" 
              placeholder="请输入密码" 
              size="large"
              show-password
            />
          </el-form-item>
          
          <el-form-item label="确认密码" prop="confirmPassword">
            <el-input 
              v-model="registerForm.confirmPassword" 
              type="password" 
              placeholder="请再次输入密码" 
              size="large"
              show-password
            />
          </el-form-item>
          
          <el-form-item label="用户类型" prop="role">
            <el-radio-group v-model="registerForm.role" size="large">
              <el-radio value="user">普通用户</el-radio>
              <el-radio value="merchant">相机商家</el-radio>
            </el-radio-group>
          </el-form-item>
          
          <el-form-item label="店铺名称" prop="shopName" v-if="registerForm.role === 'merchant'">
            <el-input 
              v-model="registerForm.shopName" 
              placeholder="请输入店铺名称" 
              size="large"
            />
          </el-form-item>
          
          <el-form-item label="店铺简介" prop="shopDescription" v-if="registerForm.role === 'merchant'">
            <el-input 
              v-model="registerForm.shopDescription" 
              type="textarea" 
              :rows="3"
              placeholder="请输入店铺简介" 
            />
          </el-form-item>
          
          <el-button 
            type="primary" 
            size="large" 
            class="register-btn"
            :loading="loading"
            @click="handleRegister"
          >
            注册
          </el-button>
        </el-form>
        
        <div class="register-footer">
          <p>
            已有账户？
            <router-link to="/login" class="login-link">立即登录</router-link>
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive, computed } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { useUserStore } from '@/stores/user'
import { Camera } from '@element-plus/icons-vue'
import { validateRules } from '@/utils/validation'

const router = useRouter()
const userStore = useUserStore()

const registerFormRef = ref(null)
const loading = ref(false)

const registerForm = reactive({
  username: '',
  nickname: '',
  email: '',
  phone: '',
  password: '',
  confirmPassword: '',
  role: 'user',
  shopName: '',
  shopDescription: ''
})

const passwordRef = computed(() => registerForm.password)

const registerRules = {
  username: validateRules.username,
  nickname: validateRules.nickname,
  email: validateRules.email,
  phone: validateRules.phone,
  password: validateRules.password,
  confirmPassword: validateRules.confirmPassword(passwordRef),
  shopName: [
    {
      validator: (rule, value, callback) => {
        if (registerForm.role === 'merchant' && !value) {
          callback(new Error('请输入店铺名称'))
        } else {
          callback()
        }
      },
      trigger: 'blur'
    }
  ]
}

const handleRegister = async () => {
  if (!registerFormRef.value) return
  
  await registerFormRef.value.validate(async (valid) => {
    if (!valid) return
    
    loading.value = true
    try {
      const { confirmPassword, ...userData } = registerForm
      await userStore.register(userData)
      ElMessage.success('注册成功，请登录')
      router.push('/login')
    } catch (error) {
      ElMessage.error(error.message || '注册失败')
    } finally {
      loading.value = false
    }
  })
}
</script>

<style lang="scss" scoped>
.register-page {
  min-height: calc(100vh - 70px - 200px);
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 40px 20px;
  background: linear-gradient(135deg, #f5e6c8 0%, #e8dcc0 100%);
}

.register-container {
  max-width: 600px;
  width: 100%;
}

.register-card {
  background: #fff;
  border-radius: 20px;
  padding: 50px;
  box-shadow: 0 20px 60px rgba(93, 78, 55, 0.15);
}

.register-header {
  text-align: center;
  margin-bottom: 40px;
}

.register-title {
  font-size: 28px;
  font-weight: bold;
  color: #333;
  margin: 16px 0 8px;
}

.register-subtitle {
  font-size: 14px;
  color: #888;
}

.register-form {
  margin-bottom: 24px;
}

.register-btn {
  width: 100%;
  margin-top: 16px;
  background: #8b6914;
  border-color: #8b6914;
  
  &:hover {
    background: #a67c00;
    border-color: #a67c00;
  }
}

.register-footer {
  text-align: center;
  font-size: 14px;
  color: #666;
}

.login-link {
  color: #8b6914;
  font-weight: 600;
  
  &:hover {
    color: #a67c00;
  }
}

@media (max-width: 640px) {
  .register-card {
    padding: 30px 20px;
  }
  
  .register-form {
    :deep(.el-form-item) {
      .el-form-item__label {
        width: 80px !important;
      }
    }
  }
}
</style>

// 167/pet-platform/src/pages/Register.jsx
import React from 'react'
import { Form, Input, Button, Card, Radio, message } from 'antd'
import { UserOutlined, LockOutlined, PhoneOutlined, MailOutlined, HomeOutlined } from '@ant-design/icons'
import { useNavigate, Link } from 'react-router-dom'
import { useDispatch, useSelector } from 'react-redux'
import { register } from '@/store/slices/userSlice'
import { validatePhone, validatePassword, validateConfirmPassword, validateName, validateEmail } from '@/utils/validate'

const Register = () => {
  const navigate = useNavigate()
  const dispatch = useDispatch()
  const [form] = Form.useForm()
  const [loading, setLoading] = React.useState(false)

  const handleRegister = async (values) => {
    setLoading(true)
    try {
      const { confirmPassword, ...registerData } = values
      dispatch(register(registerData))
      message.success('注册成功！请登录')
      setTimeout(() => {
        navigate('/login')
      }, 1000)
    } catch (error) {
      message.error(error.message || '注册失败')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div
      style={{
        minHeight: '100vh',
        background: 'linear-gradient(135deg, #ff6b35 0%, #ff8c42 100%)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
      }}
    >
      <Card
        style={{ width: '100%', maxWidth: 480, borderRadius: 12, boxShadow: '0 10px 40px rgba(0,0,0,0.2)' }}
        styles={{ body: { padding: 32 } }}
      >
        <div style={{ textAlign: 'center', marginBottom: 32 }}>
          <h1 style={{ fontSize: 28, color: '#ff6b35', marginBottom: 8 }}>🐾 注册账号</h1>
          <p style={{ color: '#666' }}>加入宠物服务平台，为您的爱宠找到优质服务</p>
        </div>

        <Form
          form={form}
          layout="vertical"
          onFinish={handleRegister}
          initialValues={{ userType: 'owner' }}
        >
          <Form.Item
            name="username"
            label="用户名"
            rules={[{ validator: validateName }]}
          >
            <Input prefix={<UserOutlined />} placeholder="请输入用户名" size="large" />
          </Form.Item>

          <Form.Item
            name="nickname"
            label="昵称"
            rules={[{ validator: validateName }]}
          >
            <Input prefix={<UserOutlined />} placeholder="请输入昵称" size="large" />
          </Form.Item>

          <Form.Item
            name="phone"
            label="手机号"
            rules={[{ validator: validatePhone }]}
          >
            <Input prefix={<PhoneOutlined />} placeholder="请输入手机号" size="large" />
          </Form.Item>

          <Form.Item
            name="email"
            label="邮箱（选填）"
            rules={[{ validator: validateEmail }]}
          >
            <Input prefix={<MailOutlined />} placeholder="请输入邮箱" size="large" />
          </Form.Item>

          <Form.Item
            name="password"
            label="密码"
            rules={[{ validator: validatePassword }]}
          >
            <Input.Password prefix={<LockOutlined />} placeholder="请输入密码（6-20位）" size="large" />
          </Form.Item>

          <Form.Item
            name="confirmPassword"
            label="确认密码"
            dependencies={['password']}
            rules={[{ validator: validateConfirmPassword(() => form.getFieldValue('password')) }]}
          >
            <Input.Password prefix={<LockOutlined />} placeholder="请再次输入密码" size="large" />
          </Form.Item>

          <Form.Item
            name="userType"
            label="注册身份"
          >
            <Radio.Group size="large" style={{ width: '100%' }}>
              <Radio.Button value="owner" style={{ width: '50%', textAlign: 'center' }}>
                我是宠主
              </Radio.Button>
              <Radio.Button value="groomer" style={{ width: '50%', textAlign: 'center' }}>
                我是宠物师
              </Radio.Button>
            </Radio.Group>
          </Form.Item>

          <Form.Item>
            <Button
              type="primary"
              htmlType="submit"
              size="large"
              block
              loading={loading}
              style={{ height: 48, fontSize: 16 }}
            >
              立即注册
            </Button>
          </Form.Item>
        </Form>

        <div style={{ textAlign: 'center', color: '#666' }}>
          已有账号？<Link to="/login">立即登录</Link>
        </div>
      </Card>
    </div>
  )
}

export default Register
