// 166/src/pages/Register/index.jsx
import React, { useState } from 'react'
import { useDispatch } from 'react-redux'
import { Link, useNavigate } from 'react-router-dom'
import { Form, Input, Button, Card, message, Checkbox } from 'antd'
import { UserOutlined, LockOutlined, MobileOutlined } from '@ant-design/icons'
import { login } from '@/store/userSlice'
import { useFormValidation, validators } from '@/hooks'
import './index.scss'

const Register = () => {
  const dispatch = useDispatch()
  const navigate = useNavigate()
  const [loading, setLoading] = useState(false)
  const [form] = Form.useForm()

  const {
    values,
    errors,
    handleChange,
    handleBlur,
    handleSubmit
  } = useFormValidation(
    { username: '', phone: '', code: '', password: '', confirmPassword: '', agree: false },
    {
      username: validators.required('请输入用户名'),
      phone: validators.phone('请输入正确的手机号'),
      code: validators.required('请输入验证码'),
      password: validators.password('密码至少6位，包含字母和数字'),
      confirmPassword: (value, allValues) => {
        if (!value) return '请确认密码'
        if (value !== allValues.password) return '两次密码输入不一致'
        return null
      }
    }
  )

  const handleRegister = async () => {
    if (!values.agree) {
      message.warning('请同意用户协议')
      return
    }

    const isValid = await handleSubmit(async (formValues) => {
      setLoading(true)
      setTimeout(() => {
        dispatch(login({
          username: formValues.username,
          phone: formValues.phone,
          nickname: formValues.username,
          role: 'consumer'
        }))
        setLoading(false)
        message.success('注册成功')
        navigate('/')
      }, 1000)
    })
  }

  const handleSendCode = () => {
    if (!values.phone || values.phone.length !== 11) {
      message.warning('请输入正确的手机号')
      return
    }
    message.success('验证码已发送：123456')
  }

  return (
    <div className="register-page">
      <div className="register-header">
        <Link to="/" className="logo">
          <span className="logo-icon">🥬</span>
          <span className="logo-text">鲜到家</span>
        </Link>
      </div>

      <Card className="register-card">
        <h2 className="register-title">注册新账号</h2>

        <Form form={form} layout="vertical" onFinish={handleRegister}>
          <Form.Item
            label="用户名"
            validateStatus={errors.username ? 'error' : ''}
            help={errors.username}
          >
            <Input
              prefix={<UserOutlined />}
              placeholder="请输入用户名"
              size="large"
              value={values.username}
              onChange={(e) => handleChange('username', e.target.value)}
              onBlur={() => handleBlur('username')}
            />
          </Form.Item>

          <Form.Item
            label="手机号"
            validateStatus={errors.phone ? 'error' : ''}
            help={errors.phone}
          >
            <Input
              prefix={<MobileOutlined />}
              placeholder="请输入手机号"
              size="large"
              value={values.phone}
              onChange={(e) => handleChange('phone', e.target.value)}
              onBlur={() => handleBlur('phone')}
            />
          </Form.Item>

          <Form.Item
            label="验证码"
            validateStatus={errors.code ? 'error' : ''}
            help={errors.code}
          >
            <div className="code-input">
              <Input
                placeholder="请输入验证码"
                size="large"
                value={values.code}
                onChange={(e) => handleChange('code', e.target.value)}
                onBlur={() => handleBlur('code')}
              />
              <Button
                size="large"
                onClick={handleSendCode}
                disabled={!values.phone || values.phone.length !== 11}
              >
                获取验证码
              </Button>
            </div>
          </Form.Item>

          <Form.Item
            label="设置密码"
            validateStatus={errors.password ? 'error' : ''}
            help={errors.password}
          >
            <Input.Password
              prefix={<LockOutlined />}
              placeholder="请输入密码（至少6位，包含字母和数字）"
              size="large"
              value={values.password}
              onChange={(e) => handleChange('password', e.target.value)}
              onBlur={() => handleBlur('password')}
            />
          </Form.Item>

          <Form.Item
            label="确认密码"
            validateStatus={errors.confirmPassword ? 'error' : ''}
            help={errors.confirmPassword}
          >
            <Input.Password
              prefix={<LockOutlined />}
              placeholder="请再次输入密码"
              size="large"
              value={values.confirmPassword}
              onChange={(e) => handleChange('confirmPassword', e.target.value)}
              onBlur={() => handleBlur('confirmPassword')}
            />
          </Form.Item>

          <Form.Item>
            <Checkbox
              checked={values.agree}
              onChange={(e) => handleChange('agree', e.target.checked)}
            >
              我已阅读并同意 <a href="#">《用户协议》</a> 和 <a href="#">《隐私政策》</a>
            </Checkbox>
          </Form.Item>

          <Button
            type="primary"
            htmlType="submit"
            size="large"
            block
            loading={loading}
          >
            注册
          </Button>
        </Form>

        <div className="register-footer">
          已有账号？<Link to="/login">立即登录</Link>
        </div>
      </Card>
    </div>
  )
}

export default Register

// 157/src/views/Register.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-pink-50 to-pink-100 flex items-center justify-center py-12">
    <div class="w-full max-w-md">
      <div class="bg-white rounded-2xl shadow-xl p-8">
        <div class="text-center mb-8">
          <div class="w-16 h-16 bg-gradient-to-br from-primary to-pink-400 rounded-full flex items-center justify-center text-white text-2xl font-bold mx-auto mb-4">
            母婴
          </div>
          <h1 class="text-2xl font-bold text-gray-800">注册账号</h1>
          <p class="text-gray-500 mt-2">创建您的母婴用品商城账号</p>
        </div>
        
        <el-form
          ref="formRef"
          :model="form"
          :rules="rules"
          label-position="top"
          class="space-y-4"
        >
          <el-form-item label="用户名" prop="username">
            <el-input
              v-model="form.username"
              placeholder="请输入用户名"
              size="large"
              :prefix-icon="User"
            />
          </el-form-item>
          
          <el-form-item label="手机号" prop="phone">
            <el-input
              v-model="form.phone"
              placeholder="请输入手机号"
              size="large"
              :prefix-icon="Cellphone"
              maxlength="11"
            />
          </el-form-item>
          
          <el-form-item label="验证码" prop="code">
            <div class="flex gap-3">
              <el-input
                v-model="form.code"
                placeholder="请输入验证码"
                size="large"
                :prefix-icon="Key"
                class="flex-1"
                maxlength="6"
              />
              <el-button
                size="large"
                :disabled="countdown > 0"
                @click="sendCode"
              >
                {{ countdown > 0 ? `${countdown}s后重新获取` : '获取验证码' }}
              </el-button>
            </div>
          </el-form-item>
          
          <el-form-item label="密码" prop="password">
            <el-input
              v-model="form.password"
              type="password"
              placeholder="请输入密码"
              size="large"
              :prefix-icon="Lock"
              show-password
            />
          </el-form-item>
          
          <el-form-item label="确认密码" prop="confirmPassword">
            <el-input
              v-model="form.confirmPassword"
              type="password"
              placeholder="请再次输入密码"
              size="large"
              :prefix-icon="Lock"
              show-password
            />
          </el-form-item>
          
          <el-form-item prop="agreement">
            <el-checkbox v-model="form.agreement">
              我已阅读并同意
              <a href="#" class="text-primary hover:underline">《用户协议》</a>
              和
              <a href="#" class="text-primary hover:underline">《隐私政策》</a>
            </el-checkbox>
          </el-form-item>
          
          <el-button
            type="primary"
            size="large"
            class="w-full py-3 !bg-gradient-to-r !from-primary !to-pink-400 !border-none"
            :loading="loading"
            @click="handleRegister"
          >
            注册
          </el-button>
        </el-form>
        
        <div class="mt-6 text-center text-sm text-gray-500">
          已有账号？
          <router-link to="/login" class="text-primary hover:underline">立即登录</router-link>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive, computed } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { User, Cellphone, Key, Lock } from '@element-plus/icons-vue'
import { registerRules, validateRequired, validatePassword } from '@/utils/validate'

const router = useRouter()

const formRef = ref(null)
const loading = ref(false)
const countdown = ref(0)

const form = reactive({
  username: '',
  phone: '',
  code: '',
  password: '',
  confirmPassword: '',
  agreement: false
})

const validateConfirmPassword = (rule, value, callback) => {
  if (value !== form.password) {
    callback(new Error('两次输入的密码不一致'))
  } else {
    callback()
  }
}

const validateAgreement = (rule, value, callback) => {
  if (!value) {
    callback(new Error('请阅读并同意用户协议'))
  } else {
    callback()
  }
}

const rules = {
  ...registerRules,
  confirmPassword: [
    validateRequired('请确认密码'),
    { validator: validateConfirmPassword, trigger: 'blur' }
  ],
  agreement: [
    { validator: validateAgreement, trigger: 'change' }
  ]
}

const sendCode = () => {
  if (!form.phone) {
    ElMessage.warning('请先输入手机号')
    return
  }
  if (!/^1[3-9]\d{9}$/.test(form.phone)) {
    ElMessage.warning('请输入正确的手机号')
    return
  }
  
  ElMessage.success('验证码已发送')
  countdown.value = 60
  
  const timer = setInterval(() => {
    countdown.value--
    if (countdown.value <= 0) {
      clearInterval(timer)
    }
  }, 1000)
}

const handleRegister = async () => {
  if (!formRef.value) return
  
  try {
    await formRef.value.validate()
    
    loading.value = true
    
    setTimeout(() => {
      loading.value = false
      ElMessage.success('注册成功，请登录')
      router.push('/login')
    }, 1000)
  } catch (error) {
    console.log('表单验证失败')
  }
}
</script>
