// 018/src/components/CategoryManagement.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { BookCategory, CategoryFormData, LogFormData } from '../types';
import { categoryService, logService } from '../services/storage';
import Modal from './Modal';

interface CategoryManagementProps {
  onCategoryChange?: () => void;
}

interface CategoryFormState {
  name: string;
}

interface FormErrors {
  name?: string;
}

interface MessageState {
  type: 'success' | 'danger';
  text: string;
}

const DEFAULT_FORM_DATA: CategoryFormState = {
  name: ''
} as const;

const CategoryManagement: React.FC<CategoryManagementProps> = ({ onCategoryChange }) => {
  const [categories, setCategories] = useState<BookCategory[]>([]);
  const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
  const [editingCategory, setEditingCategory] = useState<BookCategory | null>(null);
  const [formData, setFormData] = useState<CategoryFormState>(DEFAULT_FORM_DATA);
  const [errors, setErrors] = useState<FormErrors>({});
  const [message, setMessage] = useState<MessageState | null>(null);

  const loadCategories = useCallback((): void => {
    const allCategories: BookCategory[] = categoryService.getAll();
    setCategories(allCategories);
  }, []);

  useEffect(() => {
    loadCategories();
  }, [loadCategories]);

  const validateForm = (): boolean => {
    const newErrors: FormErrors = {};
    if (!formData.name.trim()) {
      newErrors.name = '请输入分类名称';
    } else if (formData.name.length > 50) {
      newErrors.name = '分类名称不能超过50个字符';
    }
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const openAddModal = useCallback((): void => {
    setEditingCategory(null);
    setFormData(DEFAULT_FORM_DATA);
    setErrors({});
    setIsModalOpen(true);
  }, []);

  const openEditModal = useCallback((category: BookCategory): void => {
    setEditingCategory(category);
    setFormData({ name: category.name });
    setErrors({});
    setIsModalOpen(true);
  }, []);

  const closeModal = useCallback((): void => {
    setIsModalOpen(false);
    setEditingCategory(null);
    setFormData(DEFAULT_FORM_DATA);
    setErrors({});
  }, []);

  const handleSubmit = useCallback((): void => {
    if (!validateForm()) return;

    try {
      if (editingCategory) {
        const updated: BookCategory = categoryService.update(editingCategory.id, formData.name);
        const logData: LogFormData = {
          operator: '管理员',
          content: `编辑分类：${editingCategory.name} → ${formData.name}`,
          categoryId: updated.id,
          categoryName: updated.name,
          operationType: '编辑分类'
        };
        logService.create(logData);
        setMessage({ type: 'success', text: '分类更新成功' });
      } else {
        const newCategory: BookCategory = categoryService.create(formData.name);
        const logData: LogFormData = {
          operator: '管理员',
          content: `新增分类：${formData.name}`,
          categoryId: newCategory.id,
          categoryName: newCategory.name,
          operationType: '新增分类'
        };
        logService.create(logData);
        setMessage({ type: 'success', text: '分类添加成功' });
      }

      loadCategories();
      onCategoryChange?.();
      closeModal();
    } catch (error) {
      setMessage({ 
        type: 'danger', 
        text: error instanceof Error ? error.message : '操作失败' 
      });
    }
  }, [editingCategory, formData, loadCategories, onCategoryChange, closeModal]);

  const handleDelete = useCallback((category: BookCategory): void => {
    if (!window.confirm(`确定要删除分类「${category.name}」吗？`)) return;

    try {
      categoryService.delete(category.id);
      const logData: LogFormData = {
        operator: '管理员',
        content: `删除分类：${category.name}`,
        categoryId: category.id,
        categoryName: category.name,
        operationType: '删除分类'
      };
      logService.create(logData);
      
      loadCategories();
      onCategoryChange?.();
      setMessage({ type: 'success', text: '分类删除成功' });
    } catch (error) {
      setMessage({ 
        type: 'danger', 
        text: error instanceof Error ? error.message : '删除失败' 
      });
    }
  }, [loadCategories, onCategoryChange]);

  useEffect(() => {
    if (message) {
      const timer: NodeJS.Timeout = setTimeout(() => setMessage(null), 3000);
      return (): void => clearTimeout(timer);
    }
  }, [message]);

  return (
    <div className="card">
      <div className="card-header">
        <h2 className="card-title">图书分类管理</h2>
        <button className="btn btn-primary" onClick={openAddModal}>
          + 新增分类
        </button>
      </div>

      {message && (
        <div className={`alert alert-${message.type}`}>{message.text}</div>
      )}

      <div className="table-container">
        <table>
          <thead>
            <tr>
              <th>分类名称</th>
              <th>创建时间</th>
              <th>更新时间</th>
              <th>操作</th>
            </tr>
          </thead>
          <tbody>
            {categories.map((category) => (
              <tr key={category.id}>
                <td>{category.name}</td>
                <td>{logService.getFormattedTime(category.createdAt)}</td>
                <td>{logService.getFormattedTime(category.updatedAt)}</td>
                <td>
                  <div className="table-actions">
                    <button
                      className="btn btn-secondary btn-small"
                      onClick={() => openEditModal(category)}
                    >
                      编辑
                    </button>
                    <button
                      className="btn btn-danger btn-small"
                      onClick={() => handleDelete(category)}
                    >
                      删除
                    </button>
                  </div>
                </td>
              </tr>
            ))}
            {categories.length === 0 && (
              <tr>
                <td colSpan={4}>
                  <div className="empty-state">
                    <div className="empty-state-icon">📚</div>
                    <div className="empty-state-text">暂无分类数据</div>
                    <div className="empty-state-hint">点击上方按钮添加新分类</div>
                  </div>
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      <Modal
        isOpen={isModalOpen}
        title={editingCategory ? '编辑分类' : '新增分类'}
        onClose={closeModal}
        footer={
          <>
            <button className="btn btn-secondary" onClick={closeModal}>
              取消
            </button>
            <button className="btn btn-primary" onClick={handleSubmit}>
              {editingCategory ? '保存' : '添加'}
            </button>
          </>
        }
      >
        <div className="form-group">
          <label className="form-label">
            分类名称<span className="required">*</span>
          </label>
          <input
            type="text"
            className="form-input"
            value={formData.name}
            onChange={(e) => setFormData({ name: e.target.value })}
            placeholder="请输入分类名称"
          />
          {errors.name && <div className="form-error">{errors.name}</div>}
        </div>
      </Modal>
    </div>
  );
};

export default CategoryManagement;

// 012/src/components/CategoryManagement.vue
<template>
  <div class="card">
    <div class="card-header">
      <h2 class="card-title">用品分类管理</h2>
      <button class="btn btn-primary" @click="openAddModal">
        + 新增分类
      </button>
    </div>

    <div class="table-container">
      <table class="table">
        <thead>
          <tr>
            <th>分类名称</th>
            <th>分类编码</th>
            <th>描述</th>
            <th>创建时间</th>
            <th>更新时间</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="category in categories" :key="category.id">
            <td>{{ category.name }}</td>
            <td><span class="badge badge-info">{{ category.code }}</span></td>
            <td>{{ category.description || '-' }}</td>
            <td>{{ formatDate(category.createdAt) }}</td>
            <td>{{ formatDate(category.updatedAt) }}</td>
            <td>
              <div class="table-actions">
                <button class="btn btn-sm btn-outline" @click="openEditModal(category)">
                  编辑
                </button>
                <button 
                  class="btn btn-sm btn-danger" 
                  @click="openDeleteConfirm(category)"
                  :disabled="isCategoryUsed(category.id)"
                >
                  删除
                </button>
              </div>
            </td>
          </tr>
          <tr v-if="categories.length === 0">
            <td colspan="6">
              <div class="empty-state">
                <div class="empty-state-icon">📂</div>
                <div class="empty-state-text">暂无分类数据</div>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <Modal
      v-model:visible="modalVisible"
      :title="isEdit ? '编辑分类' : '新增分类'"
      @confirm="handleSubmit"
    >
      <form @submit.prevent="handleSubmit">
        <div class="form-group">
          <label class="form-label required">分类名称</label>
          <input 
            v-model="formData.name"
            type="text"
            class="form-input"
            :class="{ error: formErrors.name }"
            placeholder="请输入分类名称"
          />
          <div v-if="formErrors.name" class="form-error">{{ formErrors.name }}</div>
        </div>

        <div class="form-group">
          <label class="form-label required">分类编码</label>
          <select 
            v-model="formData.code"
            class="form-select"
            :class="{ error: formErrors.code }"
            :disabled="isEdit"
          >
            <option value="">请选择分类编码</option>
            <option v-for="code in availableCategoryTypes" :key="code" :value="code">
              {{ categoryNames[code] }}
            </option>
          </select>
          <div v-if="formErrors.code" class="form-error">{{ formErrors.code }}</div>
        </div>

        <div class="form-group">
          <label class="form-label">描述</label>
          <textarea 
            v-model="formData.description"
            class="form-textarea"
            placeholder="请输入分类描述（可选）"
            rows="3"
          ></textarea>
        </div>
      </form>
    </Modal>

    <ConfirmDialog
      v-model:visible="confirmDialogVisible"
      title="确认删除"
      :message="`确定要删除分类「${deleteCategory?.name}」吗？此操作不可恢复。`"
      type="danger"
      @confirm="handleDelete"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, computed, onMounted } from 'vue'
import Modal from './Modal.vue'
import ConfirmDialog from './ConfirmDialog.vue'
import { storageService } from '@/services/storage'
import { validateForm, type ValidationErrors } from '@/utils/validation'
import { formatDate } from '@/utils/date'
import { categoryNames, type Category, type CategoryType } from '@/types'
import { useToast } from '@/composables/useToast'

const { success, error: toastError } = useToast()

const categories = ref<Category[]>([])
const products = ref(storageService.getProducts())

const modalVisible = ref(false)
const isEdit = ref(false)
const editingId = ref<string | null>(null)

const confirmDialogVisible = ref(false)
const deleteCategory = ref<Category | null>(null)

const formData = reactive({
  name: '',
  code: '' as CategoryType | '',
  description: ''
})

const formErrors = reactive<ValidationErrors>({})

const availableCategoryTypes = computed(() => {
  const usedCodes = categories.value.map(c => c.code)
  const allCodes: CategoryType[] = ['food', 'snack', 'grooming', 'toy', 'daily']
  
  if (isEdit.value && editingId.value) {
    const currentCode = categories.value.find(c => c.id === editingId.value)?.code
    return allCodes.filter(code => !usedCodes.includes(code) || code === currentCode)
  }
  
  return allCodes.filter(code => !usedCodes.includes(code))
})

const loadCategories = () => {
  categories.value = storageService.getCategories()
  products.value = storageService.getProducts()
}

const resetForm = () => {
  formData.name = ''
  formData.code = ''
  formData.description = ''
  Object.keys(formErrors).forEach(key => delete formErrors[key])
  isEdit.value = false
  editingId.value = null
}

const openAddModal = () => {
  resetForm()
  modalVisible.value = true
}

const openEditModal = (category: Category) => {
  resetForm()
  isEdit.value = true
  editingId.value = category.id
  formData.name = category.name
  formData.code = category.code
  formData.description = category.description
  modalVisible.value = true
}

const isCategoryUsed = (categoryId: string): boolean => {
  return products.value.some(p => p.categoryId === categoryId)
}

const openDeleteConfirm = (category: Category) => {
  if (isCategoryUsed(category.id)) {
    toastError('该分类下有商品，无法删除')
    return
  }
  deleteCategory.value = category
  confirmDialogVisible.value = true
}

const validateFormData = (): boolean => {
  const rules = {
    name: [{ required: true, message: '请输入分类名称' }],
    code: [{ required: true, message: '请选择分类编码' }]
  }

  const errors = validateForm(formData, rules)
  Object.keys(formErrors).forEach(key => delete formErrors[key])
  Object.assign(formErrors, errors)

  return Object.keys(errors).length === 0
}

const handleSubmit = () => {
  if (!validateFormData()) return

  try {
    if (isEdit.value && editingId.value) {
      storageService.updateCategory(editingId.value, {
        name: formData.name,
        code: formData.code as CategoryType,
        description: formData.description
      })
      success('分类更新成功')
    } else {
      storageService.addCategory({
        name: formData.name,
        code: formData.code as CategoryType,
        description: formData.description
      })
      success('分类添加成功')
    }

    loadCategories()
    modalVisible.value = false
    resetForm()
  } catch {
    toastError('操作失败，请重试')
  }
}

const handleDelete = () => {
  if (!deleteCategory.value) return

  try {
    storageService.deleteCategory(deleteCategory.value.id)
    success('分类删除成功')
    loadCategories()
    confirmDialogVisible.value = false
    deleteCategory.value = null
  } catch {
    toastError('删除失败，请重试')
  }
}

onMounted(() => {
  loadCategories()
})

defineExpose({
  loadCategories
})
</script>
