// 010/src/components/CategoryManagement.vue
<script setup lang="ts">
import { ref, reactive } from 'vue'
import { store } from '../store'
import { validateForm } from '../utils/validation'
import { EquipmentCategoryCode, EquipmentCategoryLabel } from '../types'
import type { Category, EquipmentCategory } from '../types'

const showForm = ref(false)
const editingCategory = ref<Category | null>(null)

const form = reactive({
  name: '',
  code: EquipmentCategoryCode.COMPUTER as EquipmentCategory,
  description: '',
})

const errors = ref<Record<string, string>>({})

const categoryCodes: { value: EquipmentCategory; label: string }[] = [
  { value: EquipmentCategoryCode.COMPUTER, label: EquipmentCategoryLabel[EquipmentCategoryCode.COMPUTER] },
  { value: EquipmentCategoryCode.PRINTER, label: EquipmentCategoryLabel[EquipmentCategoryCode.PRINTER] },
  { value: EquipmentCategoryCode.PROJECTOR, label: EquipmentCategoryLabel[EquipmentCategoryCode.PROJECTOR] },
  { value: EquipmentCategoryCode.FURNITURE, label: EquipmentCategoryLabel[EquipmentCategoryCode.FURNITURE] },
  { value: EquipmentCategoryCode.SUPPLIES, label: EquipmentCategoryLabel[EquipmentCategoryCode.SUPPLIES] },
]

function openAdd() {
  editingCategory.value = null
  form.name = ''
  form.code = EquipmentCategoryCode.COMPUTER
  form.description = ''
  errors.value = {}
  showForm.value = true
}

function openEdit(category: Category) {
  editingCategory.value = category
  form.name = category.name
  form.code = category.code
  form.description = category.description
  errors.value = {}
  showForm.value = true
}

function closeForm() {
  showForm.value = false
  editingCategory.value = null
}

function validate() {
  const result = validateForm(
    form,
    {
      name: { required: true, minLength: 2, maxLength: 50 },
      code: { required: true },
      description: { maxLength: 200 },
    },
    {
      name: '分类名称',
      code: '分类编码',
      description: '分类描述',
    }
  )
  errors.value = result.errors
  return result.isValid
}

function handleSubmit() {
  if (!validate()) return

  if (editingCategory.value) {
    store.updateCategory(editingCategory.value.id, {
      name: form.name,
      code: form.code,
      description: form.description,
    })
    store.showAlert('分类更新成功')
  } else {
    store.addCategory({
      name: form.name,
      code: form.code,
      description: form.description,
    })
    store.showAlert('分类添加成功')
  }
  closeForm()
}

function handleDelete(category: Category) {
  const used = store.state.equipments.some((e) => e.categoryId === category.id)
  if (used) {
    store.showWarning('该分类下还有设备，无法删除')
    return
  }
  store.showConfirm(`确认删除分类"${category.name}"吗？`, () => {
    store.deleteCategory(category.id)
    store.showAlert('分类删除成功')
  })
}

function getCategoryLabel(code: EquipmentCategory): string {
  return EquipmentCategoryLabel[code] || code
}
</script>

<template>
  <div class="card">
    <div class="header">
      <h2 style="font-size: 20px; font-weight: 600">设备分类管理</h2>
      <button class="btn btn-primary" @click="openAdd">+ 添加分类</button>
    </div>

    <table>
      <thead>
        <tr>
          <th>分类名称</th>
          <th>分类编码</th>
          <th>描述</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="category in store.state.categories" :key="category.id">
          <td>{{ category.name }}</td>
          <td>{{ getCategoryLabel(category.code) }}</td>
          <td>{{ category.description || '-' }}</td>
          <td>
            <button class="btn btn-sm btn-primary" @click="openEdit(category)">
              编辑
            </button>
            <button
              class="btn btn-sm btn-danger"
              style="margin-left: 8px"
              @click="handleDelete(category)"
            >
              删除
            </button>
          </td>
        </tr>
        <tr v-if="store.state.categories.length === 0">
          <td colspan="4">
            <div class="empty-state">暂无分类数据</div>
          </td>
        </tr>
      </tbody>
    </table>

    <div v-if="showForm" class="modal-overlay" @click.self="closeForm">
      <div class="modal">
        <div class="modal-title">
          {{ editingCategory ? '编辑分类' : '添加分类' }}
        </div>
        <div class="modal-body">
          <div class="form-group">
            <label class="form-label">分类名称 <span style="color: var(--danger-color)">*</span></label>
            <input
              class="form-input"
              :class="{ 'input-error': errors.name }"
              v-model="form.name"
              placeholder="请输入分类名称"
            />
            <div v-if="errors.name" class="form-error">{{ errors.name }}</div>
          </div>
          <div class="form-group">
            <label class="form-label">分类编码 <span style="color: var(--danger-color)">*</span></label>
            <select
              class="form-select"
              :class="{ 'input-error': errors.code }"
              v-model="form.code"
            >
              <option v-for="code in categoryCodes" :key="code.value" :value="code.value">
                {{ code.label }}
              </option>
            </select>
            <div v-if="errors.code" class="form-error">{{ errors.code }}</div>
          </div>
          <div class="form-group">
            <label class="form-label">分类描述</label>
            <textarea
              class="form-textarea"
              :class="{ 'input-error': errors.description }"
              v-model="form.description"
              rows="3"
              placeholder="请输入分类描述"
            ></textarea>
            <div v-if="errors.description" class="form-error">{{ errors.description }}</div>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" @click="closeForm">取消</button>
          <button class="btn btn-primary" @click="handleSubmit">
            {{ editingCategory ? '更新' : '添加' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

// 015/src/components/CategoryManagement.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { Category, SupplyCategory, FormError } from '../types';
import { SUPPLY_CATEGORIES } from '../types/constants';
import { categoryService } from '../services/storageService';
import { Modal } from './Modal';
import { validators } from '../utils/validation';

interface CategoryManagementProps {
  onCategoryChange?: () => void;
  showToast: (type: 'success' | 'error' | 'info' | 'warning', message: string) => void;
}

interface FormData {
  name: SupplyCategory;
  description: string;
}

export const CategoryManagement: React.FC<CategoryManagementProps> = ({
  onCategoryChange,
  showToast
}) => {
  const [categories, setCategories] = useState<Category[]>([]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingCategory, setEditingCategory] = useState<Category | null>(null);
  const [formData, setFormData] = useState<FormData>({
    name: '办公类',
    description: ''
  });
  const [errors, setErrors] = useState<FormError[]>([]);
  const [deleteConfirmId, setDeleteConfirmId] = useState<string | null>(null);

  const loadCategories = useCallback(() => {
    setCategories(categoryService.getAll());
  }, []);

  useEffect(() => {
    loadCategories();
  }, [loadCategories]);

  const openModal = useCallback((category?: Category) => {
    if (category) {
      setEditingCategory(category);
      setFormData({
        name: category.name,
        description: category.description
      });
    } else {
      setEditingCategory(null);
      setFormData({
        name: '办公类',
        description: ''
      });
    }
    setErrors([]);
    setIsModalOpen(true);
  }, []);

  const closeModal = useCallback(() => {
    setIsModalOpen(false);
    setEditingCategory(null);
    setErrors([]);
  }, []);

  const validateForm = useCallback((): boolean => {
    const newErrors: FormError[] = [];

    const nameError = validators.required('分类名称', formData.name);
    if (nameError) {
      newErrors.push({ field: '分类名称', message: nameError });
    }

    if (formData.description && validators.maxLength('描述', formData.description, 200)) {
      newErrors.push({
        field: '描述',
        message: validators.maxLength('描述', formData.description, 200)!
      });
    }

    if (!editingCategory && categoryService.exists(formData.name)) {
      newErrors.push({ field: '分类名称', message: '该分类已存在' });
    }

    setErrors(newErrors);
    return newErrors.length === 0;
  }, [formData, editingCategory]);

  const handleSubmit = useCallback(() => {
    if (!validateForm()) return;

    try {
      if (editingCategory) {
        const result = categoryService.update(editingCategory.id, {
          description: formData.description
        });
        if (!result.success) {
          showToast('error', result.error);
          return;
        }
        showToast('success', '分类更新成功');
      } else {
        const result = categoryService.add({
          name: formData.name,
          description: formData.description
        });
        if (!result.success) {
          showToast('error', result.error);
          return;
        }
        showToast('success', '分类添加成功');
      }

      loadCategories();
      closeModal();
      onCategoryChange?.();
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : '操作失败，请重试';
      showToast('error', errorMessage);
    }
  }, [validateForm, editingCategory, formData, loadCategories, closeModal, onCategoryChange, showToast]);

  const handleDelete = useCallback((id: string) => {
    const result = categoryService.delete(id);
    if (result.success) {
      showToast('success', '分类删除成功');
      loadCategories();
      onCategoryChange?.();
    } else {
      showToast('error', result.error);
    }
    setDeleteConfirmId(null);
  }, [loadCategories, onCategoryChange, showToast]);

  return (
    <div className="card">
      <div className="card-header">
        <h2 className="card-title">物资分类管理</h2>
        <button className="btn btn-primary" onClick={() => openModal()}>
          + 添加分类
        </button>
      </div>

      <div className="stats-grid">
        <div className="stat-card">
          <div className="stat-title">总分类数</div>
          <div className="stat-value">{categories.length}</div>
        </div>
      </div>

      <div className="table-container">
        <table className="table">
          <thead>
            <tr>
              <th>分类名称</th>
              <th>描述</th>
              <th>操作</th>
            </tr>
          </thead>
          <tbody>
            {categories.length === 0 ? (
              <tr>
                <td colSpan={3}>
                  <div className="empty-state">
                    <div className="empty-icon">📁</div>
                    <div className="empty-text">暂无分类数据</div>
                  </div>
                </td>
              </tr>
            ) : (
              categories.map((category) => (
                <tr key={category.id}>
                  <td>
                    <strong>{category.name}</strong>
                  </td>
                  <td>{category.description || '-'}</td>
                  <td>
                    <button className="btn btn-primary btn-sm" onClick={() => openModal(category)}>
                      编辑
                    </button>
                    <button
                      className="btn btn-danger btn-sm"
                      onClick={() => setDeleteConfirmId(category.id)}
                    >
                      删除
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      <Modal
        isOpen={isModalOpen}
        title={editingCategory ? '编辑分类' : '添加分类'}
        onClose={closeModal}
        footer={
          <>
            <button className="btn btn-secondary" onClick={closeModal}>
              取消
            </button>
            <button className="btn btn-primary" onClick={handleSubmit}>
              {editingCategory ? '保存' : '添加'}
            </button>
          </>
        }
      >
        <div>
          <div className="form-group">
            <label className="form-label">分类名称 *</label>
            <select
              className="form-select"
              value={formData.name}
              onChange={(e) => setFormData({ ...formData, name: e.target.value as SupplyCategory })}
              disabled={!!editingCategory}
            >
              {SUPPLY_CATEGORIES.map((cat) => (
                <option key={cat} value={cat}>
                  {cat}
                </option>
              ))}
            </select>
            {errors.find((e) => e.field === '分类名称') && (
              <div className="form-error">{errors.find((e) => e.field === '分类名称')?.message}</div>
            )}
          </div>
          <div className="form-group">
            <label className="form-label">描述</label>
            <textarea
              className="form-input"
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              placeholder="请输入分类描述"
              rows={3}
            />
            {errors.find((e) => e.field === '描述') && (
              <div className="form-error">{errors.find((e) => e.field === '描述')?.message}</div>
            )}
          </div>
        </div>
      </Modal>

      <Modal
        isOpen={!!deleteConfirmId}
        title="确认删除"
        onClose={() => setDeleteConfirmId(null)}
        footer={
          <>
            <button className="btn btn-secondary" onClick={() => setDeleteConfirmId(null)}>
              取消
            </button>
            <button
              className="btn btn-danger"
              onClick={() => deleteConfirmId && handleDelete(deleteConfirmId)}
            >
              确认删除
            </button>
          </>
        }
      >
        <p>确定要删除该分类吗？此操作无法撤销。</p>
      </Modal>
    </div>
  );
};
