// 029/src/views/login/index.vue
<template>
  <div class="login-container">
    <div class="login-card">
      <div class="login-header">
        <span class="logo">🏨</span>
        <h1 class="title">智慧酒店客房综合管理系统</h1>
        <p class="subtitle">Smart Hotel Room Management System</p>
      </div>
      <el-form
        ref="formRef"
        :model="loginForm"
        :rules="rules"
        class="login-form"
        @submit.prevent="handleLogin"
      >
        <el-form-item prop="username">
          <el-input
            v-model="loginForm.username"
            placeholder="请输入用户名"
            size="large"
            prefix-icon="User"
          />
        </el-form-item>
        <el-form-item prop="password">
          <el-input
            v-model="loginForm.password"
            type="password"
            placeholder="请输入密码"
            size="large"
            prefix-icon="Lock"
            show-password
            @keyup.enter="handleLogin"
          />
        </el-form-item>
        <el-form-item>
          <el-button
            type="primary"
            size="large"
            class="login-btn"
            :loading="loading"
            @click="handleLogin"
          >
            登 录
          </el-button>
        </el-form-item>
      </el-form>
      <div class="login-tips">
        <el-alert
          type="info"
          :closable="false"
          show-icon
          title="演示账号"
          description="用户名: admin，密码: 任意输入"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage, type FormInstance, type FormRules } from 'element-plus'
import { useUserStore } from '@/stores/user'
import { mockUser } from '@/mock'

const router = useRouter()
const userStore = useUserStore()
const formRef = ref<FormInstance>()
const loading = ref(false)

const loginForm = reactive({
  username: 'admin',
  password: '123456'
})

const rules: FormRules = {
  username: [{ required: true, message: '请输入用户名', trigger: 'blur' }],
  password: [{ required: true, message: '请输入密码', trigger: 'blur' }]
}

const handleLogin = async () => {
  if (!formRef.value) return

  try {
    await formRef.value.validate()
    loading.value = true

    setTimeout(() => {
      userStore.setUser(mockUser, mockUser.token)
      ElMessage.success('登录成功')
      loading.value = false
      router.push('/')
    }, 800)
  } catch {
    ElMessage.error('请输入正确的用户名和密码')
  }
}
</script>

<style lang="scss" scoped>
.login-container {
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  background-size: 400% 400%;
  animation: gradientBG 15s ease infinite;
}

@keyframes gradientBG {
  0% {
    background-position: 0% 50%;
  }
  50% {
    background-position: 100% 50%;
  }
  100% {
    background-position: 0% 50%;
  }
}

.login-card {
  width: 420px;
  padding: 40px;
  background: rgba(255, 255, 255, 0.95);
  border-radius: 16px;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
  backdrop-filter: blur(10px);
}

.login-header {
  text-align: center;
  margin-bottom: 40px;

  .logo {
    font-size: 56px;
    display: block;
    margin-bottom: 16px;
  }

  .title {
    font-size: 24px;
    font-weight: 600;
    color: #303133;
    margin-bottom: 8px;
  }

  .subtitle {
    font-size: 14px;
    color: #909399;
  }
}

.login-form {
  .login-btn {
    width: 100%;
    height: 48px;
    font-size: 16px;
    font-weight: 500;
  }
}

.login-tips {
  margin-top: 20px;
}
</style>

// 172/src/pages/Login/index.jsx
import { useEffect } from 'react';
import { Form, Input, Button, Card, Typography, message } from 'antd';
import { UserOutlined, LockOutlined } from '@ant-design/icons';
import { useNavigate, useLocation } from 'react-router-dom';
import { useAuth } from '../../hooks/useAuth';

const { Title } = Typography;

const Login = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const { login, isLoggedIn, isAdmin } = useAuth();
  const [form] = Form.useForm();

  useEffect(() => {
    if (isLoggedIn) {
      const from = location.state?.from?.pathname || (isAdmin ? '/admin' : '/');
      navigate(from, { replace: true });
    }
  }, [isLoggedIn, navigate, location, isAdmin]);

  const onFinish = (values) => {
    const result = login(values.username, values.password);
    if (result?.success) {
      message.success('登录成功');
      const from = location.state?.from?.pathname || (result.user.role === 'admin' ? '/admin' : '/');
      navigate(from, { replace: true });
    } else {
      message.error(result?.message || '登录失败');
    }
  };

  return (
    <div
      style={{
        minHeight: 'calc(100vh - 134px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      }}
    >
      <Card style={{ width: 400, borderRadius: 12, boxShadow: '0 4px 12px rgba(0,0,0,0.15)' }}>
      <div style={{ textAlign: 'center', marginBottom: 32 }}>
        <Title level={3} style={{ margin: 0 }}>
          🎁 文具礼品商城
        </Title>
        <p style={{ color: '#666', marginTop: 8 }}>欢迎回来，请登录您的账号</p>
      </div>

      <Form
        form={form}
        name="login"
        onFinish={onFinish}
        initialValues={{
          username: 'user',
          password: '123456',
        }}
        size="large"
      >
        <Form.Item
          name="username"
          rules={[{ required: true, message: '请输入用户名' }]}
        >
          <Input prefix={<UserOutlined />} placeholder="用户名" />
        </Form.Item>

        <Form.Item
          name="password"
          rules={[{ required: true, message: '请输入密码' }]}
        >
          <Input.Password prefix={<LockOutlined />} placeholder="密码" />
        </Form.Item>

        <Form.Item>
          <Button type="primary" htmlType="submit" block style={{ height: 48, fontSize: 16 }}>
            登录
          </Button>
        </Form.Item>
      </Form>

      <div style={{ textAlign: 'center', color: '#999', fontSize: 12 }}>
        <p style={{ margin: 0 }}>测试账号：</p>
        <p style={{ margin: '4px 0' }}>普通用户：user / 123456</p>
        <p style={{ margin: 0 }}>管理员：admin / 123456</p>
      </div>
    </Card>
    </div>
  );
};

export default Login;
