// 183/src/views/Register.vue
<template>
  <div class="register-page">
    <div class="register-container">
      <div class="register-card">
        <div class="register-header">
          <el-icon :size="48" color="#8b6914"><Camera /></el-icon>
          <h1 class="register-title">创建账户</h1>
          <p class="register-subtitle">加入复古胶片相机爱好者社区</p>
        </div>
        
        <el-form 
          ref="registerFormRef"
          :model="registerForm" 
          :rules="registerRules" 
          class="register-form"
          label-width="100px"
        >
          <el-form-item label="用户名" prop="username">
            <el-input 
              v-model="registerForm.username" 
              placeholder="请输入用户名" 
              size="large"
            />
          </el-form-item>
          
          <el-form-item label="昵称" prop="nickname">
            <el-input 
              v-model="registerForm.nickname" 
              placeholder="请输入昵称" 
              size="large"
            />
          </el-form-item>
          
          <el-form-item label="邮箱" prop="email">
            <el-input 
              v-model="registerForm.email" 
              placeholder="请输入邮箱地址" 
              size="large"
            />
          </el-form-item>
          
          <el-form-item label="手机号" prop="phone">
            <el-input 
              v-model="registerForm.phone" 
              placeholder="请输入手机号码" 
              size="large"
            />
          </el-form-item>
          
          <el-form-item label="密码" prop="password">
            <el-input 
              v-model="registerForm.password" 
              type="password" 
              placeholder="请输入密码" 
              size="large"
              show-password
            />
          </el-form-item>
          
          <el-form-item label="确认密码" prop="confirmPassword">
            <el-input 
              v-model="registerForm.confirmPassword" 
              type="password" 
              placeholder="请再次输入密码" 
              size="large"
              show-password
            />
          </el-form-item>
          
          <el-form-item label="用户类型" prop="role">
            <el-radio-group v-model="registerForm.role" size="large">
              <el-radio value="user">普通用户</el-radio>
              <el-radio value="merchant">相机商家</el-radio>
            </el-radio-group>
          </el-form-item>
          
          <el-form-item label="店铺名称" prop="shopName" v-if="registerForm.role === 'merchant'">
            <el-input 
              v-model="registerForm.shopName" 
              placeholder="请输入店铺名称" 
              size="large"
            />
          </el-form-item>
          
          <el-form-item label="店铺简介" prop="shopDescription" v-if="registerForm.role === 'merchant'">
            <el-input 
              v-model="registerForm.shopDescription" 
              type="textarea" 
              :rows="3"
              placeholder="请输入店铺简介" 
            />
          </el-form-item>
          
          <el-button 
            type="primary" 
            size="large" 
            class="register-btn"
            :loading="loading"
            @click="handleRegister"
          >
            注册
          </el-button>
        </el-form>
        
        <div class="register-footer">
          <p>
            已有账户？
            <router-link to="/login" class="login-link">立即登录</router-link>
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive, computed } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { useUserStore } from '@/stores/user'
import { Camera } from '@element-plus/icons-vue'
import { validateRules } from '@/utils/validation'

const router = useRouter()
const userStore = useUserStore()

const registerFormRef = ref(null)
const loading = ref(false)

const registerForm = reactive({
  username: '',
  nickname: '',
  email: '',
  phone: '',
  password: '',
  confirmPassword: '',
  role: 'user',
  shopName: '',
  shopDescription: ''
})

const passwordRef = computed(() => registerForm.password)

const registerRules = {
  username: validateRules.username,
  nickname: validateRules.nickname,
  email: validateRules.email,
  phone: validateRules.phone,
  password: validateRules.password,
  confirmPassword: validateRules.confirmPassword(passwordRef),
  shopName: [
    {
      validator: (rule, value, callback) => {
        if (registerForm.role === 'merchant' && !value) {
          callback(new Error('请输入店铺名称'))
        } else {
          callback()
        }
      },
      trigger: 'blur'
    }
  ]
}

const handleRegister = async () => {
  if (!registerFormRef.value) return
  
  await registerFormRef.value.validate(async (valid) => {
    if (!valid) return
    
    loading.value = true
    try {
      const { confirmPassword, ...userData } = registerForm
      await userStore.register(userData)
      ElMessage.success('注册成功，请登录')
      router.push('/login')
    } catch (error) {
      ElMessage.error(error.message || '注册失败')
    } finally {
      loading.value = false
    }
  })
}
</script>

<style lang="scss" scoped>
.register-page {
  min-height: calc(100vh - 70px - 200px);
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 40px 20px;
  background: linear-gradient(135deg, #f5e6c8 0%, #e8dcc0 100%);
}

.register-container {
  max-width: 600px;
  width: 100%;
}

.register-card {
  background: #fff;
  border-radius: 20px;
  padding: 50px;
  box-shadow: 0 20px 60px rgba(93, 78, 55, 0.15);
}

.register-header {
  text-align: center;
  margin-bottom: 40px;
}

.register-title {
  font-size: 28px;
  font-weight: bold;
  color: #333;
  margin: 16px 0 8px;
}

.register-subtitle {
  font-size: 14px;
  color: #888;
}

.register-form {
  margin-bottom: 24px;
}

.register-btn {
  width: 100%;
  margin-top: 16px;
  background: #8b6914;
  border-color: #8b6914;
  
  &:hover {
    background: #a67c00;
    border-color: #a67c00;
  }
}

.register-footer {
  text-align: center;
  font-size: 14px;
  color: #666;
}

.login-link {
  color: #8b6914;
  font-weight: 600;
  
  &:hover {
    color: #a67c00;
  }
}

@media (max-width: 640px) {
  .register-card {
    padding: 30px 20px;
  }
  
  .register-form {
    :deep(.el-form-item) {
      .el-form-item__label {
        width: 80px !important;
      }
    }
  }
}
</style>

// 170/src/pages/Register.tsx
import React from 'react';
import { Form, Input, Button, Card, message, Radio } from 'antd';
import { UserOutlined, LockOutlined, PhoneOutlined } from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import { validatePhone, validatePassword } from '../utils';

interface RegisterFormValues {
  phone: string;
  password: string;
  confirmPassword: string;
  nickname: string;
  role: 'user' | 'technician';
}

const Register: React.FC = () => {
  const navigate = useNavigate();
  const { register } = useAuth();
  const [form] = Form.useForm<RegisterFormValues>();

  const handleSubmit = async (values: RegisterFormValues) => {
    if (values.password !== values.confirmPassword) {
      message.error('两次输入的密码不一致');
      return;
    }

    try {
      const success = register(values.phone, values.password, values.nickname, values.role);
      if (success) {
        message.success('注册成功');
        navigate('/');
      } else {
        message.error('该手机号已注册');
      }
    } catch (error) {
      message.error('注册失败，请重试');
    }
  };

  return (
    <div
      style={{
        minHeight: '100vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: 'linear-gradient(135deg, #ff85c0 0%, #ff6b9d 100%)',
      }}
    >
      <Card
        style={{
          width: '420px',
          boxShadow: '0 8px 32px rgba(0,0,0,0.1)',
          borderRadius: '12px',
        }}
      >
        <div style={{ textAlign: 'center', marginBottom: '32px' }}>
          <div style={{ fontSize: '48px', marginBottom: '8px' }}>💅</div>
          <h1 style={{ margin: '0 0 8px 0', color: '#ff85c0' }}>用户注册</h1>
          <p style={{ color: '#999', margin: 0 }}>加入指爱美甲，享受专业服务</p>
        </div>

        <Form
          form={form}
          layout="vertical"
          onFinish={handleSubmit}
          initialValues={{ role: 'user' }}
        >
          <Form.Item
            name="nickname"
            label="昵称"
            rules={[
              { required: true, message: '请输入昵称' },
              { min: 2, max: 20, message: '昵称长度为2-20个字符' },
            ]}
          >
            <Input
              prefix={<UserOutlined />}
              placeholder="请输入昵称"
              size="large"
            />
          </Form.Item>

          <Form.Item
            name="phone"
            label="手机号"
            rules={[
              { required: true, message: '请输入手机号' },
              {
                validator: (_, value) => {
                  if (!value) return Promise.resolve();
                  if (validatePhone(value)) {
                    return Promise.resolve();
                  }
                  return Promise.reject(new Error('请输入正确的手机号'));
                },
              },
            ]}
          >
            <Input
              prefix={<PhoneOutlined />}
              placeholder="请输入手机号"
              size="large"
              maxLength={11}
            />
          </Form.Item>

          <Form.Item
            name="password"
            label="密码"
            rules={[
              { required: true, message: '请输入密码' },
              {
                validator: (_, value) => {
                  if (!value) return Promise.resolve();
                  if (validatePassword(value)) {
                    return Promise.resolve();
                  }
                  return Promise.reject(new Error('密码长度为6-20位'));
                },
              },
            ]}
          >
            <Input.Password
              prefix={<LockOutlined />}
              placeholder="请输入密码"
              size="large"
            />
          </Form.Item>

          <Form.Item
            name="confirmPassword"
            label="确认密码"
            rules={[
              { required: true, message: '请确认密码' },
            ]}
          >
            <Input.Password
              prefix={<LockOutlined />}
              placeholder="请再次输入密码"
              size="large"
            />
          </Form.Item>

          <Form.Item
            name="role"
            label="注册身份"
            rules={[{ required: true, message: '请选择注册身份' }]}
          >
            <Radio.Group>
              <Radio value="user">普通用户</Radio>
              <Radio value="technician">美甲师</Radio>
            </Radio.Group>
          </Form.Item>

          <Form.Item>
            <Button
              type="primary"
              htmlType="submit"
              size="large"
              block
              style={{
                background: 'linear-gradient(135deg, #ff85c0 0%, #ff6b9d 100%)',
                border: 'none',
                height: '48px',
                fontSize: '16px',
              }}
            >
              注册
            </Button>
          </Form.Item>
        </Form>

        <div style={{ textAlign: 'center', color: '#999' }}>
          已有账号？<a onClick={() => navigate('/login')}>立即登录</a>
        </div>
      </Card>
    </div>
  );
};

export default Register;
