// 043/src/components/VirtualList.tsx
import { useState, useRef, useCallback, useEffect, useMemo } from 'react'
import styles from './VirtualList.module.css'

interface VirtualListProps<T> {
  data: T[]
  itemHeight: number
  renderItem: (item: T, index: number) => React.ReactNode
  overscan?: number
  className?: string
}

function VirtualList<T>({
  data,
  itemHeight,
  renderItem,
  overscan = 5,
  className = ''
}: VirtualListProps<T>) {
  const containerRef = useRef<HTMLDivElement>(null)
  const [scrollTop, setScrollTop] = useState(0)
  const [containerHeight, setContainerHeight] = useState(0)

  useEffect(() => {
    const container = containerRef.current
    if (!container) return

    const updateHeight = () => {
      setContainerHeight(container.clientHeight)
    }

    updateHeight()
    window.addEventListener('resize', updateHeight)
    return () => window.removeEventListener('resize', updateHeight)
  }, [])

  const handleScroll = useCallback((e: React.UIEvent<HTMLDivElement>) => {
    setScrollTop(e.currentTarget.scrollTop)
  }, [])

  const visibleRange = useMemo(() => {
    const startIndex = Math.max(0, Math.floor(scrollTop / itemHeight) - overscan)
    const endIndex = Math.min(
      data.length,
      Math.ceil((scrollTop + containerHeight) / itemHeight) + overscan
    )
    return { startIndex, endIndex }
  }, [scrollTop, containerHeight, itemHeight, data.length, overscan])

  const visibleItems = useMemo(() => {
    return data.slice(visibleRange.startIndex, visibleRange.endIndex)
  }, [data, visibleRange.startIndex, visibleRange.endIndex])

  const totalHeight = data.length * itemHeight
  const offsetY = visibleRange.startIndex * itemHeight

  return (
    <div
      ref={containerRef}
      className={`${styles.container} ${className}`}
      onScroll={handleScroll}
    >
      <div style={{ height: totalHeight, position: 'relative' }}>
        <div style={{ transform: `translateY(${offsetY}px)` }}>
          {visibleItems.map((item, index) => (
            <div key={visibleRange.startIndex + index} style={{ height: itemHeight }}>
              {renderItem(item, visibleRange.startIndex + index)}
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

export default VirtualList

// 188/src/components/common/VirtualList.vue
<template>
  <div class="virtual-list" ref="containerRef" @scroll="handleScroll">
    <div class="virtual-list-phantom" :style="{ height: totalHeight + 'px' }"></div>
    <div class="virtual-list-content" :style="contentStyle">
      <slot v-for="(item, index) in visibleData" :item="item" :index="startIndex + index" name="item">
        <div class="virtual-list-item">
          {{ item }}
        </div>
      </slot>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, watch, nextTick } from 'vue'

const props = defineProps({
  data: {
    type: Array,
    default: () => []
  },
  itemHeight: {
    type: Number,
    default: 100
  },
  bufferSize: {
    type: Number,
    default: 5
  }
})

const containerRef = ref(null)
const startIndex = ref(0)
const endIndex = ref(0)
const scrollTop = ref(0)

const totalHeight = computed(() => props.data.length * props.itemHeight)

const visibleCount = computed(() => {
  if (!containerRef.value) return 10
  return Math.ceil(containerRef.value.clientHeight / props.itemHeight)
})

const visibleData = computed(() => {
  const start = Math.max(0, startIndex.value - props.bufferSize)
  const end = Math.min(props.data.length, endIndex.value + props.bufferSize)
  return props.data.slice(start, end)
})

const contentStyle = computed(() => ({
  transform: `translateY(${Math.max(0, (startIndex.value - props.bufferSize) * props.itemHeight)}px)`
}))

const handleScroll = () => {
  if (!containerRef.value) return
  scrollTop.value = containerRef.value.scrollTop
  startIndex.value = Math.floor(scrollTop.value / props.itemHeight)
  endIndex.value = startIndex.value + visibleCount.value
}

const updatePositions = async () => {
  await nextTick()
  handleScroll()
}

watch(() => props.data, () => {
  updatePositions()
}, { deep: true })

onMounted(() => {
  updatePositions()
})

defineExpose({
  scrollTo: (index) => {
    if (containerRef.value) {
      containerRef.value.scrollTop = index * props.itemHeight
    }
  }
})
</script>

<style lang="scss" scoped>
.virtual-list {
  position: relative;
  overflow-y: auto;
  height: 100%;

  .virtual-list-phantom {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    z-index: -1;
  }

  .virtual-list-content {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
  }

  .virtual-list-item {
    height: v-bind('itemHeight + "px"');
    box-sizing: border-box;
  }
}
</style>
